return {{[ [[scrolls]] ] = {2},},
{[ [[clock]] ] = {3},[ [[scrolls]] ] = {4},[ [[time]] ] = {5},},
{[ [[authors]] ] = {6},[ [[subtitle]] ] = [[Advanced MUME Time]],[ [[name]] ] = [[Clock]],[ [[help]] ] = [[This script tracks the MUME time as well as the MUME date, allowing it to report, in addition to the current time, the dawn and dusk times, the real time to dawn and dusk, the date, and the season. In addition, the clock will optionally let you know every time a minute has passed and keep you informed as to the date and season every 24 minutes.]],[ [[url]] ] = [[https://raw.githubusercontent.com/iheartdisraptor/mume/master/mudlet/scrolls/Clock.zip]],[ [[depends]] ] = {7},[ [[version]] ] = [[]],},
{[ [[authors]] ] = {8},[ [[subtitle]] ] = [[Mudlet Package Manager]],[ [[name]] ] = [[Scrolls]],[ [[help]] ] = [[Create, install, update, save, load, and reload Mudlet packages (called scrolls).]],[ [[url]] ] = [[https://raw.githubusercontent.com/iheartdisraptor/mume/master/mudlet/scrolls/Scrolls.zip]],[ [[depends]] ] = {9},[ [[version]] ] = [[1.0]],},
{[ [[authors]] ] = {10},[ [[subtitle]] ] = [[Basic Time Functions]],[ [[name]] ] = [[Time]],[ [[help]] ] = [[This scroll contains basic functions for working with time.]],[ [[url]] ] = [[https://raw.githubusercontent.com/iheartdisraptor/mume/master/mudlet/scrolls/Time.zip]],[ [[depends]] ] = {11},[ [[version]] ] = [[1.0]],},
{[1] = [[Octavia]],},
{[1] = [[Time]],},
{[1] = [[Octavia]],},
{},
{[1] = [[Octavia]],},
{},
}